# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='start_weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
