# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0002_challenge_start_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
        migrations.AddField(
            model_name='user',
            name='bench',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='deadlift',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='squat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
