# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0003_auto_20190329_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='competition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='appl.Challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messaging', to='appl.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='Image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='Message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
