# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-29 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0005_auto_20190329_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_image',
        ),
    ]
